migration tests: set CREATE_ALL_TABLES to false
seems to be the mechanism to tell the app to
_not_ create DB tables upon initialization.

migration failed with

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateTable) relation "case" already exists
[SQL:
CREATE TABLE "case" (
	id VARCHAR(50) NOT NULL,
	name TEXT NOT NULL,
	tags JSONB NOT NULL,
	PRIMARY KEY (id)
)
]
(Background on this error at: https://sqlalche.me/e/14/f405)

as of what I think is a side effect of importing

conbench.db from within migrations/env.py.