landing page: handle run.commit being `None`, tweak err handler, bump djlint (#1199)
* landing page: deal with run.commit being none

File "/app/conbench/templates/index.html", line 75, in block 'app_content'
    <a href="{{ r.run.commit.commit_url }}">{{ r.run.commit.hash[:7] }}</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'None' has no attribute 'hash'

* bump djlint to 1.23.3

* webapp: emit traceback as text/plain

for proper display